[package]
name = "verification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
algorithms = { path = "../algorithms" }

# data_structure/lazy_segment_tree

[[bin]]
name = "verification_data_structure_lazy_segment_tree_01"
path = "src/data_structure/lazy_segment_tree/main_01.rs"

[[bin]]
name = "verification_data_structure_lazy_segment_tree_02"
path = "src/data_structure/lazy_segment_tree/main_02.rs"

[[bin]]
name = "verification_data_structure_lazy_segment_tree_03"
path = "src/data_structure/lazy_segment_tree/main_03.rs"

# data_structure/union_find

[[bin]]
name = "verification_data_structure_union_find_01"
path = "src/data_structure/union_find/main_01.rs"

[[bin]]
name = "verification_data_structure_union_find_02"
path = "src/data_structure/union_find/main_02.rs"

# graph/dijkstra

[[bin]]
name = "verification_graph_dijkstra_01"
path = "src/graph/dijkstra/main_01.rs"

[[bin]]
name = "verification_graph_dijkstra_02"
path = "src/graph/dijkstra/main_02.rs"

# math/modint

[[bin]]
name = "verification_math_modint_01"
path = "src/math/modint/main_01.rs"

[[bin]]
name = "verification_math_modint_02"
path = "src/math/modint/main_02.rs"
